services:
  mongodb:
    image: mongo:7.0
    container_name: pokemon-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pokemon123
      MONGO_INITDB_DATABASE: pokemon_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - pokemon-network

  mongo-express:
    image: mongo-express:latest
    container_name: pokemon-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pokemon123
      ME_CONFIG_MONGODB_URL: mongodb://admin:pokemon123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pokemon123
    depends_on:
      - mongodb
    networks:
      - pokemon-network

volumes:
  mongodb_data:
    driver: local

networks:
  pokemon-network:
    driver: bridge
